"""add llm_models table

Revision ID: 3e58043c58cf
Revises: 78642f1d760f
Create Date: 2026-02-08 11:46:51.137910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e58043c58cf'
down_revision: Union[str, Sequence[str], None] = '78642f1d760f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'llm_models',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('platform', sa.String(50), nullable=False),
        sa.Column('model_id', sa.String(255), nullable=False),
        sa.Column('display_name', sa.String(255), nullable=False),
        sa.Column('api_key', sa.Text, nullable=False),
        sa.Column('is_enabled', sa.Boolean, default=True, server_default='true'),
        sa.Column('priority', sa.Integer, default=1, server_default='1'),
        sa.Column('created_at', sa.DateTime, server_default=sa.text('now()')),
    )
    op.create_table(
        'ai_chat_logs',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=True),
        sa.Column('note_id', sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey('notes.id', ondelete='CASCADE'), nullable=True),
        sa.Column('message', sa.Text, nullable=False),
        sa.Column('response', sa.Text, nullable=True),
        sa.Column('model_used', sa.String(255), nullable=True),
        sa.Column('tokens_used', sa.Integer, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.text('now()')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
