"""add handwritten ocr fields

Revision ID: 78642f1d760f
Revises: a622afd3b372
Create Date: 2026-02-08 11:17:21.495712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78642f1d760f'
down_revision: Union[str, Sequence[str], None] = 'a622afd3b372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_handwritten', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notes', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'extracted_text')
    op.drop_column('notes', 'is_handwritten')
    # ### end Alembic commands ###
