"""add is_favourite to colleges

Revision ID: a622afd3b372
Revises: d11233af3a5c
Create Date: 2026-02-07 11:57:33.025606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a622afd3b372'
down_revision: Union[str, Sequence[str], None] = 'd11233af3a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('is_favourite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colleges', 'is_favourite')
    # ### end Alembic commands ###
